/* Generated By:JavaCC: Do not edit this line. BoolExprParserConstants.java */
package b.SpringMID.expr.javaCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BoolExprParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 3;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 4;
  /** RegularExpression Id. */
  int STRING_LITERAL = 5;
  /** RegularExpression Id. */
  int IDENTIFIER = 6;
  /** RegularExpression Id. */
  int VARIABLE = 7;
  /** RegularExpression Id. */
  int LETTER = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<VARIABLE>",
    "<LETTER>",
    "<DIGIT>",
    "\"||\"",
    "\"&&\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
    "\"\\r\"",
    "\",\"",
  };

}
